import type { RecordType } from "@/types";

export const RECORD_TYPES: RecordType[] = [
  { id: "internal", name: "Nội khoa", active: true },
  { id: "pediatrics", name: "Nhi khoa", active: true },
  { id: "infectious", name: "Truyền nhiễm", active: true },
  { id: "gynecology", name: "Phụ khoa", active: true },
  { id: "obstetrics", name: "Sản khoa", active: true },
  { id: "neonatal", name: "Sơ sinh", active: true },
  { id: "psychiatry", name: "Tâm thần", active: true },
  { id: "dermatology", name: "Da liễu", active: true },
  { id: "hematology", name: "Huyết học – Truyền máu", active: true },
  { id: "surgery", name: "Ngoại khoa", active: true },
  { id: "burns", name: "Bỏng", active: true },
  { id: "oncology", name: "Ung bướu", active: true },
  { id: "odontology", name: "Răng Hàm Mặt", active: true },
  { id: "ent", name: "Tai Mũi Họng", active: true },
  { id: "outpatient_general", name: "Ngoại trú chung", active: true },
  { id: "outpatient_odontology", name: "Ngoại trú Răng Hàm Mặt", active: true },
  { id: "commune_level", name: "Dùng cho tuyến xã/phường", active: true },
  { id: "inpatient_traditional", name: "Nội trú Y học cổ truyền", active: true },
  { id: "outpatient_traditional", name: "Ngoại trú Y học cổ truyền", active: true },
  { id: "inpatient_pediatric_traditional", name: "Nội trú Nhi Y học cổ truyền", active: true },
  { id: "eye_trauma", name: "Mắt (chấn thương)", active: true },
  { id: "eye_anterior", name: "Mắt (Bán phần trước)", active: true },
  { id: "eye_fundus", name: "Mắt (Đáy mắt)", active: true },
  { id: "eye_glaucoma", name: "Mắt (Glocom)", active: true },
  { id: "eye_strabismus", name: "Mắt (Lác)", active: true },
  { id: "eye_pediatric", name: "Mắt trẻ em", active: true },
  { id: "rehabilitation", name: "Phục hồi chức năng", active: true },
  { id: "rehabilitation_pediatric", name: "Phục hồi chức năng nhi", active: true },
  { id: "outpatient_rehabilitation", name: "Ngoại trú phục hồi chức năng", active: true },
];
