package initdb

// createSchemaSQL is the initial PostgreSQL schema converted from the old backend.
const createSchemaSQL = `
CREATE TABLE IF NOT EXISTS "Ethnicities" (
	"Id" integer NOT NULL,
	"Name" character varying(20) NOT NULL,
	CONSTRAINT "PK_Ethnicities" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Notification" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"AppTitle" character varying(200) NOT NULL,
	"AppContent" character varying(1000) NOT NULL,
	"EmailTitle" character varying(250) NOT NULL,
	"EmailContent" text NOT NULL,
	"Type" character varying(50) NOT NULL,
	"ResourceId" integer NOT NULL,
	"ResourceUrl" character varying(100) NOT NULL,
	"CreatedAt" timestamp without time zone NOT NULL,
	CONSTRAINT "PK_Notification" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Roles" (
	"Id" integer NOT NULL,
	"Name" character varying(20) NOT NULL,
	CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Departments" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"Name" character varying(100) NOT NULL,
	"HeadUserId" integer NULL,
	"CreatedAt" timestamp without time zone NOT NULL,
	CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Users" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"RoleId" integer NOT NULL DEFAULT 1,
	"DepartmentId" integer NULL,
	"IdentityId" character varying(255) NOT NULL,
	"Email" character varying(255) NOT NULL,
	"EmailVerify" boolean NOT NULL,
	"Name" character varying(100) NOT NULL,
	"PictureUrl" character varying(500) NOT NULL,
	"CreateAt" timestamp without time zone NOT NULL,
	"UpdateAt" timestamp without time zone NOT NULL,
	"Active" boolean NOT NULL,
	"IsReceivedEmail" boolean NOT NULL DEFAULT FALSE,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Users_Departments_DepartmentId" FOREIGN KEY ("DepartmentId")
		REFERENCES "Departments" ("Id") ON DELETE SET NULL,
	CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId")
		REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Patients" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"EthnicityId" integer NOT NULL DEFAULT 56,
	"CreatedBy" integer NOT NULL,
	"Name" character varying(100) NOT NULL,
	"DateOfBirth" date NOT NULL,
	"Gender" integer NOT NULL,
	"HealthInsuranceNumber" character varying(20) NOT NULL,
	"CreatedAt" timestamp without time zone NOT NULL,
	CONSTRAINT "PK_Patients" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Patients_Ethnicities_EthnicityId" FOREIGN KEY ("EthnicityId")
		REFERENCES "Ethnicities" ("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_Patients_Users_CreatedBy" FOREIGN KEY ("CreatedBy")
		REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "UserNotifications" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"UserId" integer NOT NULL,
	"NotificationId" integer NOT NULL,
	"IsRead" boolean NOT NULL DEFAULT FALSE,
	"ReadAt" timestamp without time zone NULL,
	"IsEmailSend" boolean NOT NULL DEFAULT FALSE,
	"EmailSentAt" timestamp without time zone NULL,
	CONSTRAINT "PK_UserNotifications" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_UserNotifications_Notification_NotificationId" FOREIGN KEY ("NotificationId")
		REFERENCES "Notification" ("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_UserNotifications_Users_UserId" FOREIGN KEY ("UserId")
		REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MedicalRecords" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"PatientId" integer NOT NULL,
	"CreatedBy" integer NOT NULL,
	"RecordType" integer NULL,
	"FormCode" character varying(20) NULL,
	"StorageCode" character varying(20) NULL,
	"MedicalCode" character varying(20) NULL,
	"BedCode" character varying(20) NULL,
	"JobTitle" text NULL,
	"JobTitleCode" text NULL,
	"AddressJob" text NULL,
	"Address" character varying(255) NULL,
	"ProvinceCode" integer NULL,
	"DistrictCode" integer NULL,
	"ProvinceName" text NULL,
	"DistrictName" text NULL,
	"WardName" text NULL,
	"HealthInsuranceExpiryDate" timestamp without time zone NULL,
	"RelativeInfo" text NULL,
	"RelativePhone" text NULL,
	"PaymentCategory" integer NULL,
	"AdmissionTime" timestamp without time zone NULL,
	"AdmissionType" integer NULL,
	"ReferralSource" integer NULL,
	"AdmissionCount" text NULL DEFAULT '1',
	"HospitalTransferType" integer NULL,
	"HospitalTransferDestination" text NULL,
	"DischargeTime" timestamp without time zone NULL,
	"DischargeType" integer NULL,
	"TotalTreatmentDays" text NULL,
	"ReferralDiagnosis" text NULL,
	"ReferralCode" text NULL,
	"AdmissionDiagnosis" text NULL,
	"AdmissionCode" text NULL,
	"DepartmentDiagnosis" text NULL,
	"DepartmentCode" text NULL,
	"HasProcedure" boolean NOT NULL,
	"HasSurgery" boolean NOT NULL,
	"DischargeMainDiagnosis" text NULL,
	"DischargeMainCode" text NULL,
	"DischargeSubDiagnosis" text NULL,
	"DischargeSubCode" text NULL,
	"HasAccident" boolean NOT NULL,
	"HasComplication" boolean NOT NULL,
	"TreatmentResult" integer NULL,
	"PathologyResult" integer NULL,
	"DeathCause" integer NULL,
	"DeathTimeGroup" integer NULL,
	"DeathReason" text NULL,
	"DeathMainReason" text NULL,
	"DeathMainCode" integer NULL,
	"HasAutopsy" boolean NOT NULL,
	"DiagnosisAutopsy" text NULL,
	"DiagnosisCode" integer NULL,
	"CreatedAt" timestamp without time zone NOT NULL,
	CONSTRAINT "PK_MedicalRecords" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_MedicalRecords_Patients_PatientId" FOREIGN KEY ("PatientId")
		REFERENCES "Patients" ("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_MedicalRecords_Users_CreatedBy" FOREIGN KEY ("CreatedBy")
		REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DepartmentTransfers" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"MedicalRecordId" integer NOT NULL,
	"Name" character varying(100) NULL,
	"AdmissionTime" timestamp without time zone NULL,
	"TransferType" integer NULL,
	"TreatmentDays" character varying(5) NULL,
	CONSTRAINT "PK_DepartmentTransfers" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_DepartmentTransfers_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId")
		REFERENCES "MedicalRecords" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Hematologies" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"MedicalRecordId" integer NOT NULL,
	"RequestedById" integer NOT NULL,
	"PerformedById" integer NULL,
	"DepartmentOfHealth" character varying(255) NULL,
	"HospitalName" character varying(255) NULL,
	"FormNumber" character varying(50) NULL,
	"RoomNumber" character varying(50) NULL,
	"RequestedAt" date NULL,
	"CompletedAt" date NULL,
	"Status" integer NOT NULL,
	"RequestDescription" text NULL,
	"RedBloodCellCount" real NULL,
	"WhiteBloodCellCount" real NULL,
	"Hemoglobin" real NULL,
	"Hematocrit" real NULL,
	"Mcv" real NULL,
	"Mch" real NULL,
	"Mchc" real NULL,
	"ReticulocyteCount" real NULL,
	"PlateletCount" real NULL,
	"Neutrophil" real NULL,
	"Eosinophil" real NULL,
	"Basophil" real NULL,
	"Monocyte" real NULL,
	"Lymphocyte" real NULL,
	"NucleatedRedBloodCell" character varying(50) NULL,
	"AbnormalCells" character varying(500) NULL,
	"MalariaParasite" character varying(100) NULL,
	"Esr1h" real NULL,
	"Esr2h" real NULL,
	"BleedingTime" integer NULL,
	"ClottingTime" integer NULL,
	"BloodTypeAbo" integer NULL,
	"BloodTypeRh" integer NULL,
	CONSTRAINT "PK_Hematologies" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Hematologies_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId")
		REFERENCES "MedicalRecords" ("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_Hematologies_Users_PerformedById" FOREIGN KEY ("PerformedById")
		REFERENCES "Users" ("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_Hematologies_Users_RequestedById" FOREIGN KEY ("RequestedById")
		REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "MedicalAttachments" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"MedicalRecordId" integer NOT NULL,
	"Name" character varying(255) NOT NULL,
	"Path" character varying(255) NOT NULL,
	CONSTRAINT "PK_MedicalAttachments" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_MedicalAttachments_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId")
		REFERENCES "MedicalRecords" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MedicalRecordDetails" (
	"Id" integer NOT NULL,
	"IllnessDay" integer NULL,
	"AdmissionReason" text NULL,
	"PathologicalProcess" character varying(2000) NULL,
	"PersonalHistory" character varying(2000) NULL,
	"FamilyHistory" character varying(2000) NULL,
	"ExamGeneral" character varying(2000) NULL,
	"ExamCardio" text NULL,
	"ExamRespiratory" text NULL,
	"ExamGastro" text NULL,
	"ExamRenalUrology" text NULL,
	"ExamNeurological" text NULL,
	"ExamMusculoskeletal" text NULL,
	"ExamENT" text NULL,
	"ExamMaxillofacial" text NULL,
	"ExamOphthalmology" text NULL,
	"ExamEndocrineOthers" text NULL,
	"RequiredClinicalTests" text NULL,
	"MedicalSummary" text NULL,
	"DiagnosisMain" text NULL,
	"DiagnosisSub" text NULL,
	"DiagnosisDifferential" text NULL,
	"Prognosis" text NULL,
	"TreatmentPlan" text NULL,
	"PulseRate" character varying(5) NULL,
	"Temperature" character varying(5) NULL,
	"BloodPressure" character varying(10) NULL,
	"RespiratoryRate" text NULL,
	"BodyWeight" character varying(5) NULL,
	CONSTRAINT "PK_MedicalRecordDetails" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_MedicalRecordDetails_MedicalRecords_Id" FOREIGN KEY ("Id")
		REFERENCES "MedicalRecords" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "XRays" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"MedicalRecordId" integer NOT NULL,
	"RequestedById" integer NOT NULL,
	"PerformedById" integer NULL,
	"DepartmentOfHealth" character varying(255) NULL,
	"HospitalName" character varying(255) NULL,
	"FormNumber" character varying(50) NULL,
	"RoomNumber" character varying(50) NULL,
	"Status" integer NOT NULL,
	"RequestDescription" character varying(1000) NOT NULL,
	"RequestedAt" date NULL,
	"ResultDescription" character varying(4000) NULL,
	"DoctorAdvice" character varying(2000) NULL,
	"CompletedAt" date NULL,
	CONSTRAINT "PK_XRays" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_XRays_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId")
		REFERENCES "MedicalRecords" ("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_XRays_Users_PerformedById" FOREIGN KEY ("PerformedById")
		REFERENCES "Users" ("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_XRays_Users_RequestedById" FOREIGN KEY ("RequestedById")
		REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "HematologyStatusLogs" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"HematologyId" integer NOT NULL,
	"UpdatedById" integer NOT NULL,
	"Status" integer NOT NULL,
	"DepartmentName" character varying(255) NOT NULL,
	"CreatedAt" timestamp without time zone NOT NULL,
	CONSTRAINT "PK_HematologyStatusLogs" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_HematologyStatusLogs_Hematologies_HematologyId" FOREIGN KEY ("HematologyId")
		REFERENCES "Hematologies" ("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_HematologyStatusLogs_Users_UpdatedById" FOREIGN KEY ("UpdatedById")
		REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "MedicalRecordRiskFactors" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"MedicalRecordDetailId" integer NOT NULL,
	"Signed" integer NULL,
	"IsPossible" boolean NULL DEFAULT FALSE,
	"DurationMonth" integer NULL,
	CONSTRAINT "PK_MedicalRecordRiskFactors" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_MedicalRecordRiskFactors_MedicalRecordDetails_MedicalRecordDetailId"
		FOREIGN KEY ("MedicalRecordDetailId") REFERENCES "MedicalRecordDetails" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "XRayStatusLogs" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY,
	"XRayId" integer NOT NULL,
	"UpdatedById" integer NOT NULL,
	"Status" integer NOT NULL,
	"DepartmentName" character varying(255) NOT NULL,
	"CreatedAt" timestamp without time zone NOT NULL,
	CONSTRAINT "PK_XRayStatusLogs" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_XRayStatusLogs_Users_UpdatedById" FOREIGN KEY ("UpdatedById")
		REFERENCES "Users" ("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_XRayStatusLogs_XRays_XRayId" FOREIGN KEY ("XRayId")
		REFERENCES "XRays" ("Id") ON DELETE CASCADE
);

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint WHERE conname = 'FK_Departments_Users_HeadUserId'
	) THEN
		ALTER TABLE "Departments"
			ADD CONSTRAINT "FK_Departments_Users_HeadUserId"
			FOREIGN KEY ("HeadUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
	END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Departments_HeadUserId" ON "Departments" ("HeadUserId");
CREATE INDEX IF NOT EXISTS "IX_DepartmentTransfers_MedicalRecordId" ON "DepartmentTransfers" ("MedicalRecordId");
CREATE INDEX IF NOT EXISTS "IX_Hematologies_MedicalRecordId" ON "Hematologies" ("MedicalRecordId");
CREATE INDEX IF NOT EXISTS "IX_Hematologies_PerformedById" ON "Hematologies" ("PerformedById");
CREATE INDEX IF NOT EXISTS "IX_Hematologies_RequestedById" ON "Hematologies" ("RequestedById");
CREATE INDEX IF NOT EXISTS "IX_HematologyStatusLogs_HematologyId" ON "HematologyStatusLogs" ("HematologyId");
CREATE INDEX IF NOT EXISTS "IX_HematologyStatusLogs_HematologyId_CreatedAt" ON "HematologyStatusLogs" ("HematologyId", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_HematologyStatusLogs_UpdatedById" ON "HematologyStatusLogs" ("UpdatedById");
CREATE INDEX IF NOT EXISTS "IX_MedicalAttachments_MedicalRecordId" ON "MedicalAttachments" ("MedicalRecordId");
CREATE INDEX IF NOT EXISTS "IX_MedicalRecordRiskFactors_MedicalRecordDetailId" ON "MedicalRecordRiskFactors" ("MedicalRecordDetailId");
CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_CreatedAt" ON "MedicalRecords" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_CreatedBy" ON "MedicalRecords" ("CreatedBy");
CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_PatientId" ON "MedicalRecords" ("PatientId");
CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_RecordType" ON "MedicalRecords" ("RecordType");
CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_StorageCode" ON "MedicalRecords" ("StorageCode");
CREATE INDEX IF NOT EXISTS "IX_Notification_CreatedAt" ON "Notification" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_Patients_CreatedAt" ON "Patients" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_Patients_CreatedBy" ON "Patients" ("CreatedBy");
CREATE INDEX IF NOT EXISTS "IX_Patients_EthnicityId" ON "Patients" ("EthnicityId");
CREATE INDEX IF NOT EXISTS "IX_Patients_HealthInsuranceNumber" ON "Patients" ("HealthInsuranceNumber");
CREATE INDEX IF NOT EXISTS "IX_Patients_Name" ON "Patients" ("Name");
CREATE INDEX IF NOT EXISTS "IX_UserNotifications_IsEmailSend_NotificationId" ON "UserNotifications" ("IsEmailSend", "NotificationId");
CREATE INDEX IF NOT EXISTS "IX_UserNotifications_NotificationId" ON "UserNotifications" ("NotificationId");
CREATE INDEX IF NOT EXISTS "IX_UserNotifications_UserId_IsRead_NotificationId" ON "UserNotifications" ("UserId", "IsRead", "NotificationId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserNotifications_UserId_NotificationId" ON "UserNotifications" ("UserId", "NotificationId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_IdentityId" ON "Users" ("IdentityId");
CREATE INDEX IF NOT EXISTS "IX_Users_DepartmentId" ON "Users" ("DepartmentId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE INDEX IF NOT EXISTS "IX_Users_RoleId" ON "Users" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_XRays_MedicalRecordId" ON "XRays" ("MedicalRecordId");
CREATE INDEX IF NOT EXISTS "IX_XRays_PerformedById" ON "XRays" ("PerformedById");
CREATE INDEX IF NOT EXISTS "IX_XRays_RequestedById" ON "XRays" ("RequestedById");
CREATE INDEX IF NOT EXISTS "IX_XRayStatusLogs_UpdatedById" ON "XRayStatusLogs" ("UpdatedById");
CREATE INDEX IF NOT EXISTS "IX_XRayStatusLogs_XRayId" ON "XRayStatusLogs" ("XRayId");
CREATE INDEX IF NOT EXISTS "IX_XRayStatusLogs_XRayId_CreatedAt" ON "XRayStatusLogs" ("XRayId", "CreatedAt");
`
